---
apiVersion: v1
kind: Service
metadata:
  name: checkout
  labels:
    app.kubernetes.io/name: checkout
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: http-metrics
      port: 9400
      targetPort: 9400
  selector:
    app.kubernetes.io/name: checkout
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: checkout
  template:
    metadata:
      annotations:
        resource.opentelemetry.io/service.name: checkout
        resource.opentelemetry.io/service.namespace: ecommerce
        instrumentation.opentelemetry.io/inject-java: "opentelemetry-operator-system/otel-instrumentation"
        io.opentelemetry.discovery.logs/enabled: 'false'
      labels:
        app.kubernetes.io/name: checkout
    spec:
      containers:
        - name: checkout
          env:
            - name: SHIPPING_SERVICE_URL
              value: http://shipping:8080
          image: ghcr.io/cyrille-leclerc/webshop-checkout:latest
#          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
            - name: http-metrics
              containerPort: 9400
              protocol: TCP
      restartPolicy: Always
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: checkout
  labels:
    app.kubernetes.io/name: checkout
    # Add whatever label your Prometheus / OTel Collector "serviceMonitorSelector" expects
    # e.g. release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: checkout
  namespaceSelector:
    matchNames:
      - ecommerce
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
