create table IF NOT EXISTS orders
(
    id           bigint generated by default as identity
        primary key,
    date_created date,
    status       varchar(255)
);

create table if not exists product
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(255) not null,
    picture_url varchar(255),
    price       double precision
);

create table  if not exists order_product
(
    quantity   integer not null,
    order_id   bigint  not null
        constraint fkl5mnj9n0di7k1v90yxnthkc73
            references orders,
    product_id bigint  not null
        constraint fkhnfgqyjx3i80qoymrssls3kno
            references product,
    primary key (order_id, product_id)
);