#!/bin/bash
set -euo pipefail

source /Users/cyrilleleclerc/git/opentelemetry/opentelemetry-demo/.env

CONTAINER_NAME=pg_my_shopping_cart

# If a container with the same name exists, stop and remove it
if docker ps -a --format '{{.Names}}' | grep -Eq "^${CONTAINER_NAME}\$"; then
  echo "Removing existing container ${CONTAINER_NAME}"
  docker rm -f "${CONTAINER_NAME}"
fi

docker run -d --name "${CONTAINER_NAME}" \
   -p 5432:5432 \
   --env POSTGRES_PASSWORD=my_shopping_cart \
   --env POSTGRES_USER=my_shopping_cart \
   $POSTGRES_IMAGE
