export OPEN_TELEMETRY_AGENT_VERSION="2.9.0"
export DEPLOYMENT_ENVIRONMENT_NAME="staging"

export PYROSCOPE_AGENT_VERSION="0.15.2"
export PYROSCOPE_OTEL_AGENT_EXTENSION_VERSION="0.10.1.11"
export DATADOG_AGENT_VERSION="1.44.1"


# Declare PYROSCOPE_SERVER_ADDRESS, PYROSCOPE_BASIC_AUTH_USER, and PYROSCOPE_BASIC_AUTH_PASSWORD
# export PYROSCOPE_SERVER_ADDRESS=...
# export PYROSCOPE_BASIC_AUTH_USER=...
# export PYROSCOPE_BASIC_AUTH_PASSWORD=...