export OPEN_TELEMETRY_AGENT_VERSION="1.3.1"
export OPEN_TELEMETRY_DEPLOYMENT_ENVIRONMENT="staging"

export OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:8200
export OTEL_EXPORTER_OTLP_HEADERS="Authorization=Bearer my_secret_token"