#!/usr/bin/env bash
set +x

##########################################################################################
# PARENT DIRECTORY
# code copied from Tomcat's `catalina.sh`
##########################################################################################
# resolve links - $0 may be a softlink
PRG="$0"

while [ -h "$PRG" ]; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

# Get standard environment variables
PRGDIR=`dirname "$PRG"`

# LOAD ENVIRONMENT VARIABLES
if [ -r "$PRGDIR/setenv.sh" ]; then
  . "$PRGDIR/setenv.sh"
elif [ -r "$PRGDIR/../setenv.sh" ]; then
  . "$PRGDIR/../setenv.sh"
else
  . "$PRGDIR/../setenv.default.sh"
fi

##########################################################################################
# DOWNLOAD ELASTIC_AGENT AGENT
##########################################################################################
mkdir -p $PRGDIR/target/agent
cp  $PRGDIR/etc/elastic-agent/elasticapm.properties $PRGDIR/target/agent
$PRGDIR/../mvnw dependency:copy \
      -Dartifact=co.elastic.apm:elastic-apm-agent:$ELASTIC_AGENT_VERSION \
      -DoutputDirectory=$PRGDIR/target/agent/

$PRGDIR/../mvnw -DskipTests package


export ELASTIC_APM_SERVICE_VERSION="1.0"
export ELASTIC_APM_HOSTNAME="srv1.frontend"

echo "##################"
echo "# START FRONTEND #"
echo "##################"
echo ""
echo "ELASTIC_APM_SERVER_URL: $ELASTIC_APM_SERVER_URL"
echo "Hostname: $ELASTIC_APM_HOSTNAME"
echo "Version: $ELASTIC_APM_SERVICE_VERSION"
echo ""

java -javaagent:target/agent/elastic-apm-agent-$ELASTIC_AGENT_VERSION.jar \
     -jar target/frontend-1.0-SNAPSHOT.jar
