apiVersion: v1
kind: Service
metadata:
  name: anti-fraud
spec:
  selector:
    app: anti-fraud
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anti-fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anti-fraud
  template:
    metadata:
      labels:
        app: anti-fraud
    spec:
      containers:
      - name: anti-fraud
        image: fraud-detection:1.1-SNAPSHOT
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/compose-postgres
        - name: SPRING_DATASOURCE_USERNAME
          value: compose-postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: compose-postgres
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://lgtm:4318"
        - name: LOGGING_FILE_NAME
          value: application.log
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=anti-fraud,service.namespace=shop,service.version=1.1,deployment.environment=staging
