apiVersion: v1
kind: Service
metadata:
  name: anti-fraud
spec:
  selector:
    app: anti-fraud
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anti-fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anti-fraud
  template:
    metadata:
      labels:
        app: anti-fraud
    spec:
      containers:
      - name: anti-fraud
        image: fraud-detection:1.0-SNAPSHOT
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/compose-postgres
        - name: SPRING_DATASOURCE_USERNAME
          value: compose-postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: compose-postgres
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        - name: SERVER_PORT
          value: "8081"
        - name: LOGGING_FILE_NAME
          value: application.log
