apiVersion: v1
kind: Service
metadata:
  name: island
spec:
  selector:
    app: island
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: island
spec:
  replicas: 1
  selector:
    matchLabels:
      app: island
  template:
    metadata:
      labels:
        app: island
    spec:
      containers:
        - name: island
          image: fraud-detection:1.1-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/compose-postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: compose-postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: compose-postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://lgtm:4318"
            - name: LOGGING_FILE_NAME
              value: application.log
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=island,service.namespace=shop,service.version=1.1,deployment.environment=staging
            - name: OTEL_EXPERIMENTAL_METRICS_VIEW_CONFIG
              value: metric-config.yaml

