apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: lgtm
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: lgtm
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: lgtm
subjects:
  - kind: ServiceAccount
    name: lgtm
    namespace: default

roleRef:
  kind: ClusterRole
  name: lgtm
  apiGroup: rbac.authorization.k8s.io
