exporters:
  # see https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datadogexporter/examples/collector.yaml
  datadog:
    api:
      key: ${env:DD_API_KEY}
      site: ${env:DD_SITE:-datadoghq.com}