# Module: postgresql
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/6.8/metricbeat-module-postgresql.html

- module: postgresql
  metricsets:
    # Stats about every PostgreSQL database
    - database
    # Stats about the background writer process's activity
    - bgwriter
    # Stats about every PostgreSQL process
    - activity
    # Stats about every statement executed in the server. It requires the
    # `pg_stats_statement` library to be configured in the server.
    #- statement
  period: 10s
  hosts: ["postgres://localhost:5432?sslmode=disable&dbname=postgres"]