filebeat.inputs:
  - type: log
    enabled: true
    json.keys_under_root: true
    json.overwrite_keys: true
    paths:
      - /usr/local/var/log/my-shopping-cart/anti-fraud.log
    fields:
      service.name: frontend
    fields_under_root: true
  - type: log
    enabled: true
    json.keys_under_root: true
    json.overwrite_keys: true
    paths:
      - /usr/local/var/log/my-shopping-cart/frontend.log
    fields:
      service.name: anti-fraud
    fields_under_root: true
  - type: log
    enabled: true
    json.keys_under_root: true
    json.overwrite_keys: true
    paths:
      - /usr/local/var/log/my-shopping-cart/checkout.log
    fields:
      service.name: checkout
    fields_under_root: true
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

fields:
  env: staging

output.elasticsearch:
  hosts: ["localhost:9200"]
  protocol: "https"
  ssl.enabled: true
  ssl.verification_mode: none
  username: "elastic"
  password: "elastic"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - timestamp:
      field: "timestamp"
      layouts:
        - "UNIX_MS"
      ignore_missing: true
      test:
        - "1615986552269"
  - rename:
      fields:
        - from: "level"
          to: "log.level"
        - from: "thread"
          to: "process.thread.name"
        - from: "mdc.trace_id"
          to: "trace.id"
        - from: "mdc.span_id"
          to: "span.id"
        - from: "logger"
          to: "log.logger"
      ignore_missing: true
      fail_on_error: true
#  - add_fields:
#      when:
#        log.file.path: "/usr/local/var/log/my-shopping-cart/frontend.log"
#      target: service
#        fields:
#          name: "frontend"
#  - add_fields:
#      when:
#        log.file.path: "/usr/local/var/log/my-shopping-cart/anti-fraud.log"
#      target: service
#        fields:
#          name: "anti-fraud"
monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["localhost:9200"]
  protocol: "https"
  ssl.enabled: true
  ssl.verification_mode: none
  username: "elastic"
  password: "elastic"

# Available log levels are: error, warning, info, debug
logging.level: warning

