kind: "DatadogAgent"
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
  namespace: "datadog"
  annotations:
    agent.datadoghq.com/appsec.injector.enabled: "true"
spec:
  global:
    clusterName: "my_k8s_cluster"
    site: "datadoghq.eu"
    tags:
      - "env:production"
    credentials:
      apiSecret:
        secretName: "dd-secrets"
        keyName: "api-key"
    kubelet:
      tlsVerify: false
  features:
    clusterChecks:
      enabled: true
    orchestratorExplorer:
      enabled: true
    apm:
      instrumentation:
        enabled: true
        targets:
          - name: "default-target"
            namespaceSelector:
              matchNames:
                - "ecommerce"
            ddTraceVersions:
              java: "1"
              python: "4"
              js: "5"
              php: "1"
              dotnet: "3"
              ruby: "2"
            ddTraceConfigs:
              - name: "DD_PROFILING_ENABLED"
                value: "auto"
              - name: "DD_TRACE_DEBUG"
                value: "false"
              - name: "DD_TRACE_OTEL_ENABLED"
                value: "true"
              - name: "OTEL_TRACES_EXPORTER"
                value: "otlp"
              - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
                value: http://opentelemetry-stack-daemon-collector.opentelemetry-operator-system.svc.cluster.local:4318
    logCollection:
      enabled: true
      containerCollectAll: true
    asm:
      threats:
        enabled: true
      sca:
        enabled: true
      iast:
        enabled: true
    usm:
      enabled: true
    liveProcessCollection:
      enabled: true
  override:
    clusterAgent:
      image:
        name: "registry.datadoghq.com/cluster-agent:latest"
    nodeAgent:
      image:
        name: "registry.datadoghq.com/agent:latest"
      tolerations:
        - key: "node-role.kubernetes.io/controlplane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/etcd"
          operator: "Exists"
          effect: "NoExecute"
