#!/usr/bin/env bash
set -euo pipefail

helm repo add jetstack https://charts.jetstack.io --force-update

helm install \
  cert-manager oci://quay.io/jetstack/charts/cert-manager \
  --version v1.20.2 \
  --namespace cert-manager \
  --create-namespace \
  --set crds.enabled=true