metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  #_source.enabled: false

fields:
  env: production

output.elasticsearch:
  hosts: ["localhost:9200"]
  protocol: "https"
  username: "elastic"
  password: "elastic"
  ssl.enabled: true
  ssl.verification_mode: none

cloud:
  id: "My_Deployment:ZXVyb3BlLXdlc3QxLmdjcC5jbG91ZC5lcy5pbyQyZGM3NWQzNjI5OTA0ZjFmYWJmZDZjMTdjNDU3OGVlOSQ1YThmNTY5OTNjNDc0NjBiODJmOWZlYzQxMzQ2OGRjOA=="
  auth: "elastic:kSSP3DqJc2c9nDYUsTlcP4sZ"
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

# Available log levels are: error, warning, info, debug
logging.level: info

xpack.monitoring.enabled: true

# Stats can be access through http://localhost:5066/stats . For pretty JSON output, append ?pretty to the URL.
http.enabled: true