#!/usr/bin/env bash
set -euo pipefail

echo "Uninstalling OpenTelemetry stack..."
helm uninstall opentelemetry-stack --namespace opentelemetry-operator-system  || echo "WARNING: Could not uninstall helm release "

echo "Removing Datadog endpoint configuration..."
kubectl delete secrets --namespace opentelemetry-operator-system  --ignore-not-found=true dd-secrets

echo "OpenTelemetry stack uninstalled successfully!"

# Optional: Show remaining resources
echo ""
echo "Checking for any remaining resources..."
kubectl get pods,services,configmaps -l app.kubernetes.io/instance=opentelemetry-stack  --namespace opentelemetry-operator-system

# Remove OpenTelemetry CRDs (optional - be careful as this affects all OpenTelemetry resources)
echo "Delete CRDs"
kubectl delete crd  --namespace opentelemetry-operator-system opentelemetrycollectors.opentelemetry.io
kubectl delete crd  --namespace opentelemetry-operator-system instrumentations.opentelemetry.io
kubectl delete crd  --namespace opentelemetry-operator-system opampbridges.opentelemetry.io