# https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-kube-stack
# https://docs.datadoghq.com/opentelemetry/setup/collector_exporter/oss_setup/?tab=kubernetesdaemonset

## @param clusterName Name of the Kubernetes cluster to be used as a resource attribute in telemetry data.
## When the Kubernetes provider supports naming the cluster (eg EKS, AKS, GKE...), this value should be set accordingly.
## TODO overwrite this value
clusterName: unknown_k8s_cluster
collectors:
  daemon:
    enabled: true
    env:
      - name: DD_SITE  # Datadog intake: datadoghq.com, us3.datadoghq.com, datadoghq.eu... Defaults to datadoghq.com
        valueFrom:
          secretKeyRef:
            name: dd-secrets
            key: DD_SITE
            optional: true
      - name: DD_API_KEY
        valueFrom:
          secretKeyRef:
            name: dd-secrets
            key: DD_API_KEY
    ## @param scrape_configs_file Path to a custom Prometheus scrape_configs file to be used by the OpenTelemetry Collector.
    ## disable Prometheus scrapping as it assumes the Prometheus Node Exporter and CAdvisor are setup
    scrape_configs_file: ""
    presets:
      logsCollection:
        enabled: true
        storeCheckpoints: false
      hostMetrics:
        enabled: true
      kubeletMetrics:
        enabled: true
      kubernetesAttributes:
        enabled: true
      kubernetesEvents:
        enabled: false # disable for exporters/datadog/orchestrator_explorer/enabled: true
      # WARNING requires https://github.com/open-telemetry/opentelemetry-helm-charts/pull/2266
      kubernetesObjects:
        enabled: true
      clusterMetrics:
        enabled: true
      annotationDiscovery:
        logs:
          enabled: false
        metrics:
          enabled: true
      prometheus:
        podAnnotations:
          enabled: true
        cadvisor:
          enabled: true
      resourceDetection: # TODO enable the desired detector
        aks:
          enabled: false
        eks:
          enabled: false
        gcp:
          enabled: false
    config:
      extensions:
        datadog/extension:
          api:
            key: ${env:DD_API_KEY}
            site: ${env:DD_SITE:-datadoghq.com}
          deployment_type: daemonset
          http:
            endpoint: "localhost:9875"
            path: "/metadata"
      exporters:
        debug:
          verbosity: detailed
        datadog:
          traces:
            compute_stats_by_span_kind: true
            trace_buffer: 500
          api:
            site: ${env:DD_SITE:-datadoghq.com}
            key: ${env:DD_API_KEY}
          orchestrator_explorer:
            enabled: true
          #sending_queue:
          #  batch:
          #    flush_timeout: 10s
          #    max_size: 100
          #    min_size: 10
      connectors:
        datadog/connector:
          traces:
            compute_stats_by_span_kind: true
      processors:
        resource/fake_k8s_cluster_uid: # TODO replace by https://github.com/open-telemetry/opentelemetry-helm-charts/pull/2270
          attributes:
            - action: insert
              value: "218fc5a9-a5f1-4b54-aa05-46717d0ab26d"
              key: k8s.cluster.uid
        cumulativetodelta: {}
      receivers:
        k8sobjects:
          interval: 3m
      service:
        extensions: [datadog/extension]
        pipelines:
          traces:
            exporters:
              - datadog
              - datadog/connector
          metrics:
            exporters:
              - datadog
            processors:
              - cumulativetodelta
              # restore processors mistakenly discarded by the helm template when specifying additional receivers
              # https://github.com/open-telemetry/opentelemetry-helm-charts/issues/2254
              - k8sattributes
              - resourcedetection/env
              - resource/hostname
              - batch
          metrics/datadog_direct:
            exporters:
              - datadog
            receivers:
              - datadog/connector
          logs:
            exporters:
              - datadog
            processors:
              - k8sattributes
              - resource/fake_k8s_cluster_uid
              - resourcedetection/env
              - resource/hostname
              #- batch
            receivers: []
        telemetry:
          resource:
            deployment.environment.name: production  # TODO overwrite as needed
          metrics:
            readers:
              - periodic:
                  exporter:
                    otlp:
                      protocol: http/protobuf
                      endpoint: "https://otlp.${env:DD_SITE:-datadoghq.com}/api/v2/otlpmetrics"
                      temporality_preference: delta
                      headers:
                        - name: "dd-api-key"
                          value: "${DD_API_KEY}"
                        - name: dd-otel-metric-config
                          value: '{"resource_attributes_as_tags": true, "instrumentation_scope_metadata_as_tags": true}'
          logs:
            processors:
              - batch:
                  exporter:
                    otlp:
                      protocol: http/protobuf
                      endpoint: "https://otlp.${env:DD_SITE:-datadoghq.com}/v1/logs"
                      headers:
                        - name: "dd-api-key"
                          value: "${DD_API_KEY}"

instrumentation:
  enabled: true
  name: "otel-instrumentation"
  env:
    - name: OTEL_SEMCONV_STABILITY_OPT_IN
      value: "http,database,rpc,messaging"
    - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
      value: delta
  exporter:
    endpoint: http://opentelemetry-stack-daemon-collector.opentelemetry-operator-system.svc.cluster.local:4318
  resource:
    resourceAttributes:
      deployment.environment.name: production # overwrite as needed
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_always_on
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.28.1
    env:
      - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_KEY_VALUE_PAIR_ATTRIBUTES
        value: "true"
opentelemetry-operator:
  manager:
    collectorImage:
      repository: otel/opentelemetry-collector-contrib
      tag: "0.154.0"
kubeStateMetrics:
  enabled: true