---
apiVersion: v1
kind: Service
metadata:
  name: checkout
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  selector:
    app.kubernetes.io/name: checkout
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: checkout
  template:
    metadata:
      annotations:
        resource.opentelemetry.io/service.name: checkout
        resource.opentelemetry.io/service.namespace: ecommerce
        resource.opentelemetry.io/service.version: "1.1"
        instrumentation.opentelemetry.io/inject-sdk: "true"
      labels:
        app.kubernetes.io/name: checkout
    spec:
      containers:
        - name: checkout
          env:
            - name: SHIPPING_SERVICE_URL
              value: http://shipping:8080
          image: webshop-checkout:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
      restartPolicy: Always
