---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app.kubernetes.io/name: fraud-detection

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection
  labels:
    app.kubernetes.io/name: fraud-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fraud-detection
  template:
    metadata:
      annotations:
        resource.opentelemetry.io/service.name: fraud-detection
        resource.opentelemetry.io/service.namespace: ecommerce
        resource.opentelemetry.io/service.version: "1.1"
        resource.opentelemetry.io/deployment.environment: production
        resource.opentelemetry.io/deployment.environment.name: production
        instrumentation.opentelemetry.io/inject-sdk: "true"
      labels:
        app.kubernetes.io/name: fraud-detection
    spec:
      containers:
        - name: fraud-detection
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ecommerce
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/ecommerce
            - name: SPRING_DATASOURCE_USERNAME
              value: ecommerce
          image: webshop-fraud-detection:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
