apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: run-k6-from-configmap
spec:
  parallelism: 4
  script:
    configMap:
      name: k6-load-test-webshop-frontend
      file: k6.js
  runner:
    env:
      - name: FRONTEND_URLS
        value: "http://frontend:8080"