#!/usr/bin/env bash

set -x


SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Print the directory
echo "Script folder: $SCRIPT_DIR"

kubectl create configmap k6-load-test-webshop-frontend --from-file $SCRIPT_DIR/../load-generator/src/main/k6/k6.js --dry-run=client -o yaml | kubectl apply -f -
