---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: shipping
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shipping
  template:
    metadata:
      annotations:
        resource.opentelemetry.io/service.name: shipping
        resource.opentelemetry.io/service.namespace: ecommerce
        resource.opentelemetry.io/service.version: "1.1"
        instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app.kubernetes.io/name: shipping
    spec:
      containers:
        - name: shipping
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: ecommerce
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/ecommerce
            - name: SPRING_DATASOURCE_USERNAME
              value: ecommerce
          image: webshop-shipping:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      restartPolicy: Always
