---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  ports:
    - name: "8088"
      port: 8088
      targetPort: 8088
  selector:
    app.kubernetes.io/name: shipping
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app.kubernetes.io/name: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shipping
  template:
    metadata:
      annotations:
        resource.opentelemetry.io/service.name: shipping
        resource.opentelemetry.io/service.namespace: ecommerce
        resource.opentelemetry.io/service.version: "1.1"
        resource.opentelemetry.io/deployment.environment: production
        resource.opentelemetry.io/deployment.environment.name: production
        instrumentation.opentelemetry.io/inject-sdk: "true"
      labels:
        app.kubernetes.io/name: shipping
    spec:
      containers:
        - name: shipping
          env:
            - name: SERVER_PORT
              value: "8088"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ecommerce
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/ecommerce
            - name: SPRING_DATASOURCE_USERNAME
              value: ecommerce
          image: webshop-shipping:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
              protocol: TCP
      restartPolicy: Always
