---
apiVersion: v1
kind: Service
metadata:
  name: warehouse
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: warehouse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: warehouse
  template:
    metadata:
      annotations:
        resource.opentelemetry.io/service.name: warehouse
        resource.opentelemetry.io/service.namespace: ecommerce
        resource.opentelemetry.io/service.version: "1.1"
        instrumentation.opentelemetry.io/inject-sdk: "true"
      labels:
        app.kubernetes.io/name: warehouse
    spec:
      containers:
        - name: warehouse
          env:
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
          image: webshop-warehouse:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      restartPolicy: Always
