#!/usr/bin/env bash

##########################################################################################
# PARENT DIRECTORY
# code copied from Tomcat's `catalina.sh`
##########################################################################################
# resolve links - $0 may be a softlink
PRG="$0"

while [ -h "$PRG" ]; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

# Get standard environment variables
PRGDIR=`dirname "$PRG"`

# LOAD ENVIRONMENT VARIABLES
if [ -r "$PRGDIR/../../setenv.sh" ]; then
  . "$PRGDIR/../../setenv.sh"
else
  . "$PRGDIR/../../setenv.default.sh"
fi
if [ -r "$PRGDIR/../setenv.sh" ]; then
  . "$PRGDIR/../setenv.sh"
fi

set -x
TRACE_ID="3a9feafd8886675cc023760fbe80669"
curl -u "$TEMPO_USERNAME:$TEMPO_PASSWORD" https://$TEMPO_ENDPOINT/tempo/api/traces/$TRACE_ID



