admissionWebhooks:
  certManager:
    enabled: false
  autoGenerateCert:
    enabled: true
manager:
  collectorImage:
    repository: otel/opentelemetry-collector-contrib
    tag: 0.134.1
  autoInstrumentationImage:
    java:
      repository: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java
      tag: 2.19.0
  createRbacPermissions: true
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
