clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    pipeline_stages:
      - regex:
          expression: '(level|lvl|severity)=(?P<level>\\w+)'
      - labels:
          level:
    static_configs:
      - labels:
          job: my-stdin-logs
